<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <HaleyProject Condition="'$(HaleyProject)' == ''">$(MSBuildProjectDirectory)\..\..</HaleyProject>
  </PropertyGroup>
  <Import Project="$(HaleyProject)\HaleyProject\Haley.Source.Props" />
  <Import Project="$(HaleyProject)\HaleyProject\Haley.Version.Props" />
  <Import Project="$(HaleyProject)\HaleyProject\Haley.Paths.Props" />
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <RootNamespace>Haley</RootNamespace>
    <AssemblyName>Haley.Helpers.Web</AssemblyName>
    <SignAssembly>True</SignAssembly>
    <IsPackable>true</IsPackable>
    <AssemblyOriginatorKeyFile>..\..\HaleyProject\HaleyProject.snk</AssemblyOriginatorKeyFile>
    <PackageIcon>Haley.png</PackageIcon>
    <Version>$(HaleyHelpersWebVersion)</Version>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReleaseNotes>Web api helpers to ease the setup</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>$(ProjectBaseUrl)Helpers.Web</PackageProjectUrl>
    <RepositoryUrl>$(ProjectBaseUrl)Helpers.Web</RepositoryUrl>
    <Description>A tiny tool to quickly setup a webAPI.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\**" />
    <Compile Remove="Utils\AuthHandlers\**" />
    <Content Remove="Abstractions\**" />
    <Content Remove="Utils\AuthHandlers\**" />
    <EmbeddedResource Remove="Abstractions\**" />
    <EmbeddedResource Remove="Utils\AuthHandlers\**" />
    <None Remove="Abstractions\**" />
    <None Remove="Utils\AuthHandlers\**" />
  </ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<WarningLevel>2</WarningLevel>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

  <ItemGroup>
    <None Include="..\..\HaleyProject\Haley.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sessions\Database\MariaDB\schema.sql"
                      LogicalName="Haley.BrowserSessions.Database.MariaDB.schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <!--<PackageReference Condition="'$(TargetFramework)'=='net6.0'" Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.28" />-->
    <!--<PackageReference Condition="'$(TargetFramework)'=='net8.0'" Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.3" />
    <PackageReference Condition="'$(TargetFramework)'=='net9.0'" Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.2" />-->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <Choose>
    <When Condition="Exists('$(HaleyHelpersDBProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyHelpersDBProj)">
          <Name>HaleyHelpersDB</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Helpers.DB" Version="$(HaleyHelpersDBVersion)" />
      </ItemGroup>
    </Otherwise>
  </Choose>

</Project>
